---
title: "US water withdrawals"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { icon: "fa-question-circle", href: "https://github.com/anguswg-ucsb/water_use", align: right }
    theme: cosmo
    orientation: rows
    source_code: embed
    vertical_layout: fill
---


```{r setup, include = FALSE}
library(shiny)
library(flexdashboard)
library(shinyWidgets)

library(dplyr)
library(tidyr)
library(janitor)
library(stringr)
library(dataRetrieval)
library(USAboundaries)
library(sf)

library(DT)
library(highcharter)
library(RColorBrewer)
source('utils.R')
```


```{r context="server"}
#Initialize Maps 
# output$conusMap     <- renderLeaflet({ basemap() })
state_lst <- data.frame(state = state.name)
county_lst <- us_counties() %>% 
  st_drop_geometry()

water_use <<- reactive({
    df <- readNWISuse(stateCd= state()$state_name[1], countyCd = county()) %>%
            clean_names()
})

# output$countyMap <- renderLeaflet({ pop_map(pop) })

```

NWIS water use data {data-icon="fa-tint"}
=====================================

Inputs {.sidebar}
-------------------------------------

### Model Filters
```{r}
# dateRangeInput("dateTS", label = "Date Range Input",
#                start = "1993-01-01",
#                end = "2018-12-31",
#                min = "1993-01-01",
#                max = "2018-12-31",
#                format = "yyyy mm dd",
#                weekstart = 1)

# state, county, usage and sector UI outputs
uiOutput("stateSelect")
uiOutput("countySelect")
# uiOutput("usageSelect")
uiOutput("sectorSelect")


```

```{r context="server"}
# sector_lst <- data.frame(source = c("consumptive", "withdrawals", "public",
#                                     "domestic","commericial","industrial", "mining",
#                                     "irrigation_total","irrigation_crop", "irrigation_golf",
#                                     "livestock", "aquaculture", "total_thermoelectric",
#                                     "fossil_fuel", "nuclear", "hydro",
#                                     "geothermal", "fossil_fuel", "wastewater"))
sector_lst <- data.frame(source = c("Total Self Supplied Withdrawals Fresh", "Surface Water Withdrawals Fresh", "Groundwater Withdrawals Fresh"))

# usage <- data.frame(source = c("consumptive", "withdrawals"))

# State input 
output$stateSelect <- renderUI({
   selectInput("stateSearch", "Choose state:",
               as.list(unique(county_lst$state_name)),
               multiple= FALSE,
               selectize = TRUE)
})

# County input
output$countySelect <- renderUI({
   selectInput("countySearch", "Choose county:",
               choices = NULL,
               multiple= FALSE,
               selectize = TRUE)
})
# Usage input
# output$usageSelect <- renderUI({
#    selectInput("usageSearch", "Sink:",
#                choices = c("consumptive", "withdrawals"),
#                multiple= FALSE,
#                selectize = TRUE)
# })
# Sector input
output$sectorSelect <- renderUI({
   selectInput("sectorSearch", "Choose sector:",
               choices = as.list(sector_lst),
               multiple= FALSE,
               selectize = TRUE)
})

```

### 
```{r}
actionButton("submitButton", label = "Enter", icon("search"))
```


```{r context="server"}
# Make state input a reactive value
state <- reactive({
  if(is.null(input$stateSearch)){
    NULL
  } else {
    filter(county_lst, state_name == input$stateSearch)
  }
  })
# output$stateText <- renderPrint({
#   state()
#   })
# usage <- reactive({
#   input$usageSearch
# })
# output$usageText <- renderPrint({
#   usage()
#   })
# When state input changes, county choices update to respective state
observeEvent(state(), {
  choices <- state()$name
  updateSelectInput(session, inputId = "countySearch", choices = choices)

})

# Make county input a reactive value
county <- reactive({
  input$countySearch
})

# Reactivity test for county input
output$countyText <- renderPrint({
   county()
  })

# Make sector input a reactive value
sector <- reactive({
  input$sectorSearch
})
```



Row {.tabset}
----------------------------------------------
### Water withdrawals
```{r}
highchartOutput("waterUseGraph")
```

```{r context = "server"}
# county water use graph, reactive to state, county, and sector inputs
waterUseData <- eventReactive(input$submitButton, {
     df <- tidy_sectors(water_use())
     # cols <- viridisLite::viridis(12)
     # cols <- substr(cols, 0, 7)
     
      if(!is.null(input$sectorSearch)) {
          df <- df %>% filter(str_detect(sector, sector()))
          df$sector <-  gsub(" Self Supplied Surface Water Withdrawals Fresh in Mgal d", "", df$sector)
          df$sector <-  gsub(" Surface Water Withdrawals Fresh in Mgal d", "", df$sector)
          df$sector <-  gsub(" Self Supplied Surface Water Withdrawals Fresh in Mgal", "", df$sector)
          df$sector <-  gsub(" Self Supplied Groundwater Withdrawals Fresh in Mgal d", "", df$sector)
          df$sector <-  gsub(" Total Self Supplied Withdrawals Fresh in Mgal d", "", df$sector)
          num = length(unique(df$sector))
          cols = colorRampPalette(brewer.pal(6, "Paired"))(num)
          highchart() %>%
              hc_add_series(df, type = "column", hcaes(x = year, y = withdrawals, group = "sector")) %>%
              hc_colors(cols) %>% 
              hc_add_theme(hc_thm = hc_theme_elementary())
      } else {
        NULL
      }
})

# Render water use plot after action button is clicked
output$waterUseGraph <- renderHighchart({
        waterUseData()
      })
```

### Population
```{r}
highchartOutput("popGraph")
```
 
```{r context = "server"}
popData <- eventReactive(input$submitButton, {
         df <- readNWISuse(stateCd= state()$state_name[1], countyCd = "ALL") %>%
            clean_names()
     
      if(!is.null(input$sectorSearch)) {
          state_pop <- get_pop_data(df)
          
          county_pop <- state_pop %>%
              filter(county_nm == paste0(county(), " County"))
          state_pop <- state_pop %>%
              group_by(year) %>%
              summarize(total_pop = sum(population), avg_growth = mean(growth_rate, na.rm = TRUE))

          num = length(unique(df$county_nm))
          cols = colorRampPalette(brewer.pal(6, "Paired"))(num)
          
          highchart() %>%
              hc_add_theme(hc_thm = hc_theme_flat2()) %>%
              hc_yAxis_multiples(list(title = list(text = "Population"),
                                      max = max(county_pop$population)*1.2,
                                      showFirstLabel = TRUE,
                                      showLastLabel = TRUE,
                                      opposite = FALSE),
                                 list(title = list(text = "Growth Rate %"),
                                      max = 20,
                                      showLastLabel=FALSE,
                                      opposite = TRUE)) %>%
              hc_add_series(state_pop, name = "State Growth %", type = "column", hcaes(x = year, y = avg_growth), yAxis = 1) %>%
              hc_add_series(county_pop, name = "County Growth %", type = "column", hcaes(x = year, y = growth_rate), yAxis = 1) %>%
              hc_add_series(county_pop, name = "County population", type = "line", hcaes(x = year, y = population), yAxis = 0) %>%
              hc_colors(c("darkcyan", "lightblue", "darkred")) %>% 
              hc_chart(plotBorderWidth = 1, plotBorderColor = '#b4b4b4', height = NULL)
      } else {
        NULL
      }
})

output$popGraph <- renderHighchart({
        popData()
      })
```


### Data table 
```{r}
DTOutput("waterDT")
```

``` {r context = "server"}
# county water use data table, reactive to state, county, and sector inputs
waterData <- eventReactive(input$submitButton, {
     df <- tidy_sectors(water_use())
     if(!is.null(input$sectorSearch)) {
       df <- df %>% filter(str_detect(sector, sector()))
       datatable(df, fillContainer = TRUE)
    } else {
        NULL
      }
}) 
     # else if(!is.null(input$usageSearch) && !is.null(input$sectorSearch)) {
     #   df <- df %>%
     #     filter(str_detect(sector, usage())) %>%
     #      filter(str_detect(sector, sector()))
     #   DT::datatable(df, fillContainer = TRUE)
     # }
# Render water use data table after action button is clicked
output$waterDT <- renderDT({
  waterData()
})

```





